### ISSUE TITLE
Bug with rotating rectangle.

### ISSUE THREAD

**Issue by jdbence** [CadetEditor/CadetEngine-as#3] opened 2013-06-21 15:02 UTC
I'm running the air app on Windows 7.
In the editor, I created a rigid body rectangle with a fixed position. If I rotate it, it's draw position is offset from its physics body when you preview. I attached an image with an image to show what I'm talking about.

![ddd](https://f.cloud.github.com/assets/389775/687712/4c9e3124-da83-11e2-835d-6a000928feb2.png)

**Comment by robsilv** [comment] 2013-06-21 15:10
Thanks @jdbence, will look into it! I'm currently reviewing the physics editor, it's still very beta at the mo.

**Comment by robsilv** [comment] 2013-06-21 17:44
Hi @jdbence, are you building this scene in the AIR version of the editor? If so, can you send me the saved XML file?

**Comment by jdbence** [comment] 2013-06-22 22:40
Yes, I was building it the AIR version of the editor. I sent you the XML to your gmail.

**Comment by robsilv** [comment] 2013-06-25 15:44
Cool thanks. A few bugs with the Box2D editor slipped through the net with the last major update. I've loaded your file and can reproduce the error, looking into fixing it, along with a few other things as we speak.

**Comment by robsilv** [comment] 2013-06-25 17:46
Hi @jdbence, I've found the error, it's due to the conversion from degrees to radians being commented out [here](https://github.com/CadetEditor/CadetEngine-as/blob/master/cadet2DBox2D/src/cadet2DBox2D/components/behaviours/RigidBodyBehaviour.as#L237). If you uncomment and republish it should solve the problem in the engine. I'll commit this to the engine and republish the editor with the next round of updates. Thanks for the report!

**Comment by robsilv** [comment] 2013-08-16 09:00
Hi @jdbence, this should now be properly resolved with the latest release of the editor, available on the [downloads](http://cadeteditor.github.io/downloads/index.html) page. If you experience any other issues with the Box2D scenes, please try debugging by adding a [DebugDrawProcess](https://github.com/CadetEditor/CadetEngine-as/blob/master/cadet2DBox2D/src/cadet2DBox2D/components/processes/DebugDrawProcess.as) to the scene and let me know!

**Closed as completed by robsilv** 2013-08-16 09:00 UTC
